### ISSUE TITLE
never push generated files

### ISSUE THREAD

**Issue by amit10may** [Lavanya-nrg/sensitive_data_guard#1]
virtual env folder should never to pushed to git
i think you ignored some kf earlier notes on setting up .gitignore file. when you create repo from github ui, it allows to add a .gitignore file automatically, you just need to choose right language. in case you choose python, then github will fill in all standard ignore patterns.
if in doubt, look at any standard python lib repos to learn what a typical .gitignore file should cover.
typically vevnv, vscode, logs, *.log, *.bak, build, dist folders are ignored

**Comment by Lavanya-nrg** [comment]
issues resolved in master in #1
