### ISSUE TITLE
naming confusion

### ISSUE THREAD

**Issue by amit10may** [Lavanya-nrg/sensitive_data_guard#2]
your package name and folder name is totally different. to avoid such possible confusion for end user of you package, both should be same

eg choose sensitiveinfo as package name instead of pkgLavanya (which anyway is a bad name from case point of view and also looks weird with pkg prefix) 

if in confusion, simply look at any standard python libs and their github repos how their naming is setup

**Comment by Lavanya-nrg** [comment]
all issue resolved in master branch #1 #2
